name: Build & Release
on:
    push:
        tags:
            - "v*.*.*"
permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.23"
            - name: Release with GoReleaser
              uses: goreleaser/goreleaser-action@v2
              with:
                  args: release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
