name: Build & Release
on:
    push:
        tags:
            - "v*.*.*"
permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, darwin, windows]
                goarch: [amd64, arm64]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.23"
            - name: Build
              run: |
                  CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
                  go build -trimpath -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" \
                    -o builds/fyora_${{ matrix.goos }}_${{ matrix.goarch }}/fyora

            - name: Publish Release
              uses: softprops/action-gh-release@v1
              with:
                  files: builds/**/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
