name: Build & Release
on:
    push:
        tags:
            - "v*.*.*"
permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, darwin, windows]
                goarch: [amd64, arm64]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.23"
            - name: Build
              run: goreleaser release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
